---
- name: Deploy Scientific Calculator
  hosts: localhost
  tasks:
    - name: Pull the Docker image from Docker Hub
      community.docker.docker_image:  # Specify the collection
        name: mahimaiyer/scientific-calculator
        tag: latest
        pull: yes # Use state instead of pull

    - name: Run the Docker container
      community.docker.docker_container:  # Specify the collection
        name: scientific_calculator
        image: mahimaiyer/scientific-calculator:latest
        state: started
        restart_policy: always
        detach: yes
