---
- name: Deploy Scientific Calculator
  hosts: localhost
  tasks:
    - name: Ensure Docker service is started
      service:
        name: docker
        state: started

    - name: Pull Docker Image from Docker Hub
      docker_image:
        name: "mahimaiyer/scientific-calculator"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result

    - name: Start Docker service
      service:
        name: docker
        state: started
    - name: Running container
      shell: docker run -it -d --name calculator mahimaiyer/scientific-calculator
