--
- name: Deploy Scientific Calculator
  hosts: localhost
  tasks:
    - name: Ensure Docker service is started
      service:
        name: docker
        state: started

    - name: Pull Docker Image from Docker Hub
      docker_image:
        name: "mahimaiyer/scientific-calculator"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result

    - name: Run Docker container
      docker_container:
        name: scientific_calculator
        image: mahimaiyer/scientific-calculator



